# Generated by Django 4.2.1 on 2023-06-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_habitacion_estado_habitacion_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='disponible',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='ocupada',
            field=models.BooleanField(default=False),
        ),
    ]
