# Generated by Django 4.2.1 on 2023-06-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categoria_options_comunicado_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicado',
            options={'ordering': ['-fecha_envio']},
        ),
        migrations.AddField(
            model_name='comunicado',
            name='autor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
